# Generated by Django 3.0.5 on 2020-04-28 08:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0002_auto_20200428_1424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='StatusTable',
        ),
    ]
