# Generated by Django 3.0.5 on 2020-04-28 09:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0003_auto_20200428_1426'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusTable',
            new_name='Status',
        ),
    ]
