# Generated by Django 3.0.5 on 2020-04-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
